#!/usr/bin/env python3
"""Build the combined third-party vocabulary Stage A workspace.

Current adapters:
- beijing_start1
- renjiao_start1

This builder preserves source occurrences and creates a cross-source surface index only.
It deliberately does NOT mint stable ThirdPartyIDs before sense-aware identity resolution,
and it does NOT execute the final diff against Klose Stable Vocabulary identities.
"""
from __future__ import annotations

import csv
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "anki" / "klose"
OUT = BASE / "third_party_vocabulary" / "staging"

ADAPTERS = [
    ("beijing_start1", BASE / "source_reference" / "beijing_start1_staging" / "occurrences.csv"),
    ("renjiao_start1", BASE / "source_reference" / "renjiao_start1_staging" / "occurrences.csv"),
]

OCC_FIELDS = [
    "SourceOccurrenceKey", "SourceID", "SourceBook", "Grade", "Semester",
    "SourceRow", "Word", "MatchKey", "British", "American", "Definition",
    "SourceFile",
]
SURFACE_FIELDS = [
    "MatchKey", "DisplayForms", "Definitions", "SourceIDs", "SourceBooks",
    "OccurrenceCount", "SurfaceState", "IdentityResolutionStatus", "MergeAuthorized",
]


def read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise SystemExit(f"Missing adapter occurrences: {path}")
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def write_csv(path: Path, fields: list[str], rows: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        w.writeheader()
        for row in rows:
            w.writerow({k: "" if row.get(k) is None else str(row.get(k, "")) for k in fields})


def unique_join(values: list[str]) -> str:
    return "|".join(dict.fromkeys(v for v in values if v))


def main() -> None:
    occurrences: list[dict[str, str]] = []
    adapter_counts: Counter[str] = Counter()
    seen_occ: set[str] = set()

    for source_id, path in ADAPTERS:
        rows = read_csv(path)
        for row in rows:
            if row.get("SourceID") != source_id:
                raise SystemExit(f"Adapter SourceID mismatch in {path}: {row.get('SourceID')} != {source_id}")
            key = row.get("SourceOccurrenceKey", "")
            if not key or key in seen_occ:
                raise SystemExit(f"Duplicate/empty SourceOccurrenceKey: {key}")
            seen_occ.add(key)
            occurrences.append({f: row.get(f, "") for f in OCC_FIELDS})
            adapter_counts[source_id] += 1

    grouped: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in occurrences:
        key = row.get("MatchKey", "")
        if not key:
            raise SystemExit(f"Empty MatchKey: {row.get('SourceOccurrenceKey')}")
        grouped[key].append(row)

    surfaces: list[dict[str, str]] = []
    for key in sorted(grouped):
        rows = grouped[key]
        source_ids = list(dict.fromkeys(r["SourceID"] for r in rows))
        state = "cross-source-exact-overlap" if len(source_ids) > 1 else "single-source-surface"
        surfaces.append({
            "MatchKey": key,
            "DisplayForms": unique_join([r["Word"] for r in rows]),
            "Definitions": unique_join([r["Definition"] for r in rows]),
            "SourceIDs": "|".join(source_ids),
            "SourceBooks": unique_join([f"{r['SourceID']}:{r['SourceBook']}" for r in rows]),
            "OccurrenceCount": str(len(rows)),
            "SurfaceState": state,
            "IdentityResolutionStatus": "pending",
            "MergeAuthorized": "no",
        })

    OUT.mkdir(parents=True, exist_ok=True)
    write_csv(OUT / "occurrences.csv", OCC_FIELDS, occurrences)
    write_csv(OUT / "surface_index.csv", SURFACE_FIELDS, surfaces)
    write_csv(
        OUT / "cross_source_exact_overlap.csv",
        SURFACE_FIELDS,
        [r for r in surfaces if r["SurfaceState"] == "cross-source-exact-overlap"],
    )

    state_counts = Counter(r["SurfaceState"] for r in surfaces)
    readme = f"""# Third-party Vocabulary — Stage A Combined Workspace

Generated by `tools/build_third_party_vocabulary_stage_a.py`.

Current adapters:

```text
beijing_start1  occurrences = {adapter_counts['beijing_start1']}
renjiao_start1  occurrences = {adapter_counts['renjiao_start1']}
```

Combined staging facts:

```text
Total source occurrences       = {len(occurrences)}
Distinct normalized MatchKeys  = {len(surfaces)}
Cross-source exact overlaps    = {state_counts['cross-source-exact-overlap']}
Single-source surfaces         = {state_counts['single-source-surface']}
```

This is not yet the final Third-party Vocabulary Identity Registry.
`MatchKey` is only a candidate grouping key. Every surface remains
`IdentityResolutionStatus=pending` and `MergeAuthorized=no` until sense-aware
identity resolution is completed.

No stable ThirdPartyID is minted here, because an unresolved surface may later
split into multiple target-sense identities.

Final Klose diff is explicitly out of scope for Stage A.
"""
    (OUT / "README.md").write_text(readme, encoding="utf-8")

    print(f"Third-party Stage A occurrences = {len(occurrences)}")
    print(f"Third-party Stage A MatchKeys = {len(surfaces)}")
    print("Stable ThirdPartyID minted = no")
    print("Final Klose diff executed = no")


if __name__ == "__main__":
    main()
